In [1]:
import pandas as pd
pd.set_option("display.max_columns", None)

df_binance = pd.read_csv('../data/raw/Binance_Data_1m_2021_2024.csv')
df_binance.head()

,symbol,open_time,open,high,low,close,volume,close_time,quote_asset_volume,number_of_trades,taker_buy_base_volume,taker_buy_quote_volume,ignore
0,BTCUSDT,1609459200000,28923.63,28961.66,28913.12,28961.66,27.457032,1609459259999,7.943820e+05,1292,16.777195,485390.826825,0
1,BTCUSDT,1609459260000,28961.67,29017.50,28961.01,29009.91,58.477501,1609459319999,1.695803e+06,1651,33.733818,978176.468202,0
2,BTCUSDT,1609459320000,29009.54,29016.71,28973.58,28989.30,42.470329,1609459379999,1.231359e+06,986,13.247444,384076.854453,0
3,BTCUSDT,1609459380000,28989.68,28999.85,28972.33,28982.69,30.360677,1609459439999,8.800168e+05,959,9.456028,274083.075142,0
4,BTCUSDT,1609459440000,28982.67,28995.93,28971.80,28975.65,24.124339,1609459499999,6.992262e+05,726,6.814644,197519.374888,0

In [ ]:
df_binance['open_time_dt'] = pd.to_datetime(df_binance['open_time'], unit='ms', utc=True)
df_binance['minute'] = df_binance['open_time_dt'].dt.floor('min')
df_binance['date'] = df_binance['open_time_dt'].dt.date

df_binance['benchmark_close'] = df_binance['close']

In [3]:
df_binance.head()

,symbol,open_time,open,high,low,close,volume,close_time,quote_asset_volume,number_of_trades,taker_buy_base_volume,taker_buy_quote_volume,ignore,open_time_dt,minute,date,benchmark_close
0,BTCUSDT,1609459200000,28923.63,28961.66,28913.12,28961.66,27.457032,1609459259999,7.943820e+05,1292,16.777195,485390.826825,0,2021-01-01 00:00:00+00:00,2021-01-01 00:00:00+00:00,2021-01-01,28961.66
1,BTCUSDT,1609459260000,28961.67,29017.50,28961.01,29009.91,58.477501,1609459319999,1.695803e+06,1651,33.733818,978176.468202,0,2021-01-01 00:01:00+00:00,2021-01-01 00:01:00+00:00,2021-01-01,29009.91
2,BTCUSDT,1609459320000,29009.54,29016.71,28973.58,28989.30,42.470329,1609459379999,1.231359e+06,986,13.247444,384076.854453,0,2021-01-01 00:02:00+00:00,2021-01-01 00:02:00+00:00,2021-01-01,28989.30
3,BTCUSDT,1609459380000,28989.68,28999.85,28972.33,28982.69,30.360677,1609459439999,8.800168e+05,959,9.456028,274083.075142,0,2021-01-01 00:03:00+00:00,2021-01-01 00:03:00+00:00,2021-01-01,28982.69
4,BTCUSDT,1609459440000,28982.67,28995.93,28971.80,28975.65,24.124339,1609459499999,6.992262e+05,726,6.814644,197519.374888,0,2021-01-01 00:04:00+00:00,2021-01-01 00:04:00+00:00,2021-01-01,28975.65

In [4]:
df_binance.to_csv('../data/processed/binance_1m_processed.csv', index=False)